site_name: Literally FNF! Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: yellow
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: switch to light mode
      primary: purple
      accent: brown
  logo: assets/logo.png

extra:
  generator: false

plugins:
  - search
  - section-index

nav:
  - Home: index.md
  - Main:
    - Visuals:
      - main/visuals.md
      - Entities:
        - main/visuals/entities.md
        - Attributes: main/visuals/entities/attributes.md